kind: List
apiVersion: v1
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    name: kubernetes-cockpit
    labels:
      name: kubernetes-cockpit
  spec:
    replicas: 1
    selector:
      name: kubernetes-cockpit
    template:
      metadata:
        labels:
          name: kubernetes-cockpit
      spec:
        containers:
        - name: kubernetes-cockpit
          image: cockpit/kubernetes:latest
          ports:
          - containerPort: 9090
            protocol: TCP
          env:
          - name: KUBE_INSECURE
            value: 'false'
          - name: COCKPIT_KUBE_INSECURE
            value: 'false'
          - name: G_MESSAGES_DEBUG
            value: 'all'
          - name: KUBERNETES_CA_DATA
            valueFrom:
               secretKeyRef:
                 name: cockpit-kubeca
                 key: kubeca.crt
          volumeMounts:
            - name: cockpit-cert
              mountPath: /var/run/secrets/ws-certs.d
        volumes:
          - name:  cockpit-cert
            secret:
               secretName: cockpit-clientcert
- kind: Service
  apiVersion: v1
  metadata:
    name: kubernetes-cockpit
    labels:
      name: kubernetes-cockpit
  spec:
    type: NodePort
    ports:
    - protocol: TCP
      port: 443
      targetPort: 9090
    selector:
      name: kubernetes-cockpit